### ISSUE TITLE
Layout issues Timeseries chart

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#13]
There are some graphical issues left on the timeseries chart:

- [ ] The colors of the reference lines (black and red) are perhaps a bit too primary
- [x] The colors that chart lines / bars get are arbitrary shades of blue
- [x] The label of alarms (especially active ones) becomes too long on small screens, needs a "..." after some width
- [x] Labels (of reference lines and of the Y axis) are drawn in the middle of the line, need to be positioned elsewhere
- [x] The tooltip follows the mouse, request was in the top left corner of the chart as in Lizard, I think this is also OK, but it's not exactly to spec
- [x] It appears to decide whether to draw circles for the data points entirely at random
- [x] My work on the ticks to show from parramatta-mobile-dashboard needs to be copied (and then improved)
- [x] In general on a small screen (like a sideways phone) things look messy.

**Comment by gijs** [comment]
- Changed Line to Area (to be able to style with a gradient)
- Removed Tooltip animation
- Disabled white dots (didn't add any value to the readability/usability of chart)

![screen shot 2017-10-23 at 11 25 31](https://user-images.githubusercontent.com/7193/31881777-e73943d4-b7e4-11e7-846b-d9d7efb520bc.jpg)

**Comment by gijs** [comment]
- Styled the Y Axis label

![screen shot 2017-10-23 at 11 40 30](https://user-images.githubusercontent.com/7193/31882428-0be1c448-b7e7-11e7-9ffd-062f32d04a56.jpg)

**Comment by gijs** [comment]
ok for now
