### ISSUE TITLE
client configuration - how to make the new design configurable

### ISSUE THREAD

**Issue by Derryrover** [nens/parramatta-dashboard#249]
client configuration - how to make the new design configurable
https://xd.adobe.com/view/9e19e521-626c-4072-8531-5e6b2d46785d-cb4a/screen/94bd98c9-de58-47fc-b257-65caae508863

**Comment by Derryrover** [comment]
@joeriverheijden 

Hi Joeri,

We have currently the parramatta as the only paying customer for this board right?
Are any of the other demo parramatta dashboard still needed? (made to demo to other Australian customers)
In other words do we need to make the app backwards compatible with the current (old) design?

kr Tom

**Comment by lexvand** [comment]
Outdated by development by @remcogerlich
