### ISSUE TITLE
Grote versie alarmen tile

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#25]
Mail van Ber was:

> Grote tile:
> 
> - Een lijstje met warnings - threshold levels gaan zijn Minor, Moderate, Major
> 
> - Per location/timeseries alleen de hoogst gebreachte threshold.
> 
> - Boven het lijstje zou ik graag de info over de laatste berekening tonen, met een tekst zoals: Last calculation results covering period from 10/19/2017 09:00 GMT+8 untill 10/19/2017 18:00 GMT+8
> 
> 
> Voor nr monitored locations:
> 
> <asset/Timeseries name> <level> Warning  last calculated value <last calculated value> exceeds threshold of <threshold value> <unit>
> 
> ....
> 
> Voorbeeld:
> 
> Last calculation results covering period from 10/19/2017 09:00 GMT+8 untill 10/19/2017 18:00 GMT+8
> 
> Marsden Weir (Toongabbie Ck) : Minor Warning - breached since 10/19/2017 16:24 GMT+8 last calculated value 1.4 exceeds threshold of 1 [mLGH]
> 
> Redbank Rd (Toongabbie Ck) : Major Warning - breached since 10/19/2017 15:14 GMT+8 last calculated value 2.4 exceeds threshold of 2 [mLGH]
> 
> Blacktown Ck (Int. Peace Park) : No Warning - last calculated value 1.9 below threshold of 2 [mLGH]

Overlegd:
- Alle alarmen, in een vaste volgorde (bijv gesorteerd op naam)
- We tonen de naam van het alarm, niet van het asset (want eenvoudiger)
- Als nu een warning, dan niveau daarvan aangeven, en kleur

**Comment by gijs** [comment]
I'll start with this issue tomorrow or monday 👍

**Comment by gijs** [comment]
Tomorrow FOR REAL!

**Comment by gijs** [comment]
Ik heb nu dit:
![screen shot 2017-11-01 at 10 53 49](https://user-images.githubusercontent.com/7193/32269546-f824b6d2-bef2-11e7-972a-980c3669747c.jpg)

Wat bedoel je met "kleur aangeven"?

**Comment by gijs** [comment]
See https://github.com/nens/parramatta-dashboard/pull/45

**Comment by remcogerlich** [comment]
Merged, cool. Kleur bedoelde ernstig / middel / laag, maar dat doen we nog even niet.
