### ISSUE TITLE
Ook losse WMS lagen kunnen toevoegen aan map tiles

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#26]

**Comment by gijs** [comment]
Staan geconfigureerd in https://parramatta.lizard.net/ - svp overnemen

**Comment by gijs** [comment]
https://geoserver9.lizard.net/geoserver/parramatta/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=gauges&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&ZINDEX=1004&UUID=3cd5c72&SLUG=gauges&COMPLEXWMSOPTIONS=%5Bobject%20Object%5D&URL=https%3A%2F%2Fgeoserver9.lizard.net%2Fgeoserver%2Fparramatta%2Fwms&SRS=EPSG%3A3857&OPACITY=1&BBOX=16813700.23783365,-3996739.3349752952,16818592.2076439,-3991847.3651650455

**Comment by gijs** [comment]
Fixed when https://github.com/nens/parramatta-dashboard/pull/42 gets merged
