### ISSUE TITLE
Ook verschillende icoontjes voor warnings gebruiken op de kaart ivm kleurenblindheid

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#27]

**Comment by gijs** [comment]
Het schijnt inderdaad het beste te zijn om niet enkel kleur te gebruiken ter indicatie.
Ik zal icoontjes maken.
Een simpele kleurtest is overigens converteren naar greyscale. Als je dan geen verschil ziet, is de kans groot dat een gebruiker met kleurenblindheid het ook niet ziet in de website.

**Comment by gijs** [comment]
Fixes once https://github.com/nens/parramatta-dashboard/pull/43 gets merged
