### ISSUE TITLE
Legend: Load new legend data on route change / map rerender

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#3]
Problem: The legend sometimes shows up blank. 
Maybe [this code](https://github.com/nens/parramatta-dashboard/blob/master/src/components/Legend.js#L66) is doing the lookup wrong?

**Comment by gijs** [comment]
This is a weird one... I'll look at it later today

**Comment by gijs** [comment]
Didn't find the time to look at it yet...

**Comment by remcogerlich** [comment]
Is a CORS issue, doesn't happen on the server only in development.
