### ISSUE TITLE
[Legend] unit bij de schaal tonen

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#33]
zit in observation type

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parramatta dashboard: Legenda issues [2u]](https://trello.com/c/tbmr3f57/2338-parramatta-dashboard-legenda-issues-2u)

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parramatta dashboard: Legenda issues [2u]](https://trello.com/c/tbmr3f57/2338-parramatta-dashboard-legenda-issues-2u)

**Comment by remcogerlich** [comment]
Wordt gewoon "LEGEND"

**Comment by remcogerlich** [comment]
En waardes moeten van hoog naar laag lopen.
