### ISSUE TITLE
[Legend] loopt bij waterdiepte van 0 tot 1 ipv 0 tot 2

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#34]

**Comment by remcogerlich** [comment]
https://parramatta.lizard.net/api/v3/wms/?service=wms&request=getlegend&layer=scenarios%3A1542%3Adepth-dtri&steps=15&style=Blues%3A0.0%3A2.0

Is een bug in het endpoint, hij snapt dat de limits 0 en 2 zijn maar geeft toch alleen tussen 0 en 1 terug.

https://parramatta.lizard.net/admin/raster_server/colormapdefinition/39/change/?_changelist_filters=q%3Dblues loopt ook van 0 tot 1.
