### ISSUE TITLE
title and logo's

### ISSUE THREAD

**Issue by beralbers** [nens/parramatta-dashboard#53]
For the logo for FISH can remove ‘ River Flood Interactive Dashboard’ top left and replace with ‘ Parramatta River Flood Information System Hub’  and then in the centre bigger and in bold ‘FISH DASHBOARD’ 

I am happy to keep the council logo but we should add somewhere at the top the SES logo, OEH logo and SWC logo.

![image](https://user-images.githubusercontent.com/3777412/33137289-d889b96a-cfa7-11e7-9e0e-5c64260adb9c.png)
![image](https://user-images.githubusercontent.com/3777412/33137294-dc81ad20-cfa7-11e7-8cc4-57ad6dbbc0e3.png)
![image](https://user-images.githubusercontent.com/3777412/33160643-4e123aec-d01e-11e7-8443-aadf686c2851.png)

**Comment by gijs** [comment]
Mogen de logo's wegvallen in mobile mode?

**Comment by beralbers** [comment]
klant is akkoord: alleen het CoP logo overhouden (zoals huidige implementatie) is prima

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Logo's in balk [1u]](https://trello.com/c/p3vR97WH/2487-parramatta-logos-in-balk-1u)
