### ISSUE TITLE
accepting terms and conditions gets me nowhere (Internet Explorer)

### ISSUE THREAD

**Issue by beralbers** [nens/parramatta-dashboard#54]
go to parramatta.lizard.net/clients/parramatta/
Log in to Lizard
accept terms and conditions
stare at a white web-page (refresh sends you back to T&C)

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parramatta dashboard: Terms & Conditions updaten [2u]](https://trello.com/c/cLhXTg1Y/2336-parramatta-dashboard-terms-conditions-updaten-2u)

**Comment by remcogerlich** [comment]
Error is (in Edge, neem aan ook in IE)

SCRIPT438: Object doesn't support property or method 'values'
react-dom.production.min.js (185,300)

Kortweg de react-dom library die we gebruiken is niet compatibel met Edge/IE, moeten we iets mee.

**Comment by remcogerlich** [comment]
Fixed op staging (lang leve babel-polyfill).

**Comment by gijs** [comment]
👍

**Comment by remcogerlich** [comment]
Dit is nog open, er bleken andere problemen met IE nog niet verholpen.

**Comment by remcogerlich** [comment]
Kan met de versie van nu geen problemen meer reproduceren in IE.

**Comment by gijs** [comment]
Klinkt goed :)
