### ISSUE TITLE
Wish: Link field from Map popup to another detail page

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#55]
Client wish: Having a link from a map popup to a detail page that belongs to it. 
Visually:
![screen shot 2017-12-04 at 15 50 42](https://user-images.githubusercontent.com/7193/33558764-0a3a1858-d90b-11e7-8d4c-b49c96b4faab.jpg)

We could solve this by adding an optional, configurable `linkTo` field, which takes any link.

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Link from popup to tile](https://trello.com/c/YIFHpDmm/2488-parramatta-link-from-popup-to-tile)

**Comment by remcogerlich** [comment]
The popup already shows a list of timeseries (and soon, a raster/point intersection); we can easily add a function that finds a graph tile that contains the same timeseries or intersection, and let it link to that (to the first, if there are multiple -- that shouldn't happen).

**Comment by gijs** [comment]
@remcogerlich dit heb je nu werkend toch?
