### ISSUE TITLE
Achtergrondkaart: Satellite met labels ipv deze topo map

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#56]
SVP Mapbox' Satellite met labels instellen ipv deze topo map

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Menu-knop met een paar opties [1d]](https://trello.com/c/VDtypFBV/2489-parramatta-menu-knop-met-een-paar-opties-1d)

**Comment by remcogerlich** [comment]
@gijs: heb jij daar een WMS URL van?

**Comment by gijs** [comment]
Mapbox biedt z/x/y png's aan. Die van ons Mapbox account is:
https://{s}.tiles.mapbox.com/v3/nelenschuurmans.iaa79205/{z}/{x}/{y}.png

**Comment by gijs** [comment]
👍
