### ISSUE TITLE
Contactpagina

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#58]
Klant wil een contactpagina.
Optie voorgelegd om middels een verticaal gecentreerd, rechts uitgelijnd labeltje naar een speciaal hiervoor ingerichte pagina te linken.

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Menu-knop met een paar opties [1d]](https://trello.com/c/VDtypFBV/2489-parramatta-menu-knop-met-een-paar-opties-1d)

**Comment by remcogerlich** [comment]
Inhoud van de pagina is er nog niet.

**Comment by remcogerlich** [comment]
Settings weg op mobiel.

**Comment by gijs** [comment]
old, closing
