### ISSUE TITLE
time select in dashboard

### ISSUE THREAD

**Issue by beralbers** [nens/parramatta-dashboard#59]
Currently we can configure in json what temporal window to display relative to "NOW".

The user would like an button/option to change "NOW" for post-event evaluation.

If we change "NOW" back in time, the entire temporal view of the dashboard (all tiles) should shift with it.

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Menu-knop met een paar opties [1d]](https://trello.com/c/VDtypFBV/2489-parramatta-menu-knop-met-een-paar-opties-1d)

**Comment by gijs** [comment]
Menu button was added in https://github.com/nens/parramatta-dashboard/pull/65
