### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by beralbers** [nens/parramatta-dashboard#60]
Line "now" should be more obvious
timeseries with different intervals in one graph (waterlevel line at 5 min, bar chart at 15 min interval)
legend items to be configured (parameter of timeserie or "text")
thresholds (kleuring in json instelbaar?)
name of big tile differing form small tile

**Comment by beralbers** [comment]
period -12hr +12hr
data tonen met interval waarop opgeslagen

**Comment by remcogerlich** [comment]
Line "now": voorbeeld van FEWS

**Comment by remcogerlich** [comment]
Raster Intersections zijn backend model, die gebruiken dan zijn er reference lines.

**Comment by remcogerlich** [comment]
Extra reference lines that are not alarms to be configured in the JSON

**Comment by remcogerlich** [comment]
Line color of alarms will be set in the backend

**Comment by remcogerlich** [comment]
Bij open tile een uitgebreide titel gebruiken, die altijd volledig zichtbaar is (evt over meerdere regels)

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Parramatta] Solve the graph issues [~6d]](https://trello.com/c/i3bNRuKV/2491-parramatta-solve-the-graph-issues-6d)
