### ISSUE TITLE
Ook punt intersecties met een labeltje op de kaart laten zien

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#61]
Voor elke punt/raster interesectie waar een grafiek voor is:
- Een schildje op de kaart laten zien
- Met een kleur afhankelijk van alarms op diezelfde intersectie
- Zonder timeseries dingen in de popup
- Maar met een link naar de desbetreffende tile

**Comment by gijs** [comment]
Kan dicht?

**Comment by remcogerlich** [comment]
Moet nog getest worden, heeft data op staging nodig.
