### ISSUE TITLE
Andere link voor regenanimatie

### ISSUE THREAD

**Issue by remcogerlich** [nens/parramatta-dashboard#62]
Uit mail Ber: https://reg.bom.gov.au/nsw/flood/sydney.shtml

**Comment by remcogerlich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[parramatta] Make tiles configurable [0.5d]](https://trello.com/c/3hsU3oRs/2485-parramatta-make-tiles-configurable-05d)

**Comment by remcogerlich** [comment]
Moet ook nog een andere link hebben voor de GIF. Beide nu instelbaar in admin.

**Comment by gijs** [comment]
@remcogerlich kan dicht denk ik?

**Comment by remcogerlich** [comment]
Er moet nog een link aangeleverd worden. Kan wel ingesteld worden dus geen software-todo meer, maar ik laat hem nog staan omdat het nog gedaan moet worden.

**Comment by gijs** [comment]
old, closing
