### ISSUE TITLE
Settings werken niet in IE

### ISSUE THREAD

**Issue by lisannewapstra** [nens/parramatta-dashboard#71]
Ik kan de settingspagina openen in IE, en zie 'date/time settings' en 'background layers' staan, maar deze zijn niet klikbaar, hetgeen ze wel in andere browsers zijn. 
![image](https://user-images.githubusercontent.com/33685743/35632130-168bcb74-06a6-11e8-8380-7cad6c9d87f5.png)

**Comment by gijs** [comment]
old, closing
