### ISSUE TITLE
Date/time settings

### ISSUE THREAD

**Issue by lisannewapstra** [nens/parramatta-dashboard#72]
Fijn om erbij te zetten of het om lokale tijd of UTZ gaat of iets anders.

**Comment by remcogerlich** [comment]
Het gaat om lokale tijd, en de app toont overal lokale tijd. Het is voor lokale gebruikers in Sydney die, denk ik, niet zullen aannemen dat het misschien iets anders dan lokale tijd zou kunnen zijn. En de instelling is voor gebruik tijdens trainingen. Dus voor nu zet ik deze even op 'won't fix'.
