### ISSUE TITLE
Error: Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by gijs** [nens/parramatta-dashboard#9]
> 
> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

![screen shot 2017-10-18 at 11 37 28](https://user-images.githubusercontent.com/7193/31711536-bdfc1626-b3f8-11e7-9a02-ce119e6f4e15.jpg)

This is probably caused by the (improper) use of [`componentDidUpdate()`](https://github.com/nens/parramatta-dashboard/blob/master/src/components/TimeseriesTile.js#L66).
`setState()` should not be used inside `componentDidUpdate()` as it can cause infinite render loops. This is definitely bad practice. 

More info: 
- https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/update/postrender_with_componentdidupdate.html
- https://stackoverflow.com/questions/37937250/componentdidupdate-setstate-reactjs-infinite-loop

My $0.02 on this:

We should let our redux code figure out what the final state will be. Final, as in: the result of async calls. This final state should be passed to the components once. This removes the need for `componentDidUpdate()`.

**Comment by remcogerlich** [comment]
The reason I call it is because the same thing needs to happen both on the first time it is mounted and on all subsequent updates. So calling componentDidUpdate avoids code duplication. They could of course call the same function, but I don't agree that this is necessarily wrong.

**Comment by gijs** [comment]
Maybe you're right about that. I just wanted my console error free ;)

**Comment by gijs** [comment]
Not blocking...
